### PR TITLE
Customize

### PR DESCRIPTION
**Pull request by gfreezy**

### CODE REVIEW

**Comment by rwultsch** [comment]
There are a bunch of good ideas here. Improving out support of multiple slaves is definitely on our todo list. If you wrote this for fun, it is nice work. If you are interested in using our code long term we should talk about the right abstractions.

**Comment by gfreezy** [comment]
Are there any plans?

**Comment by rwultsch** [comment]
I am going to go out on paternity leave in 3 weeks. We should have code out for:
1. Easy point in time recovery.
2. Shard migration. 

I will be out for 4 months and it is likely there will be little progress during that time. At some point we should change how we do service discovery. We also need gtid support. Those are not pressing needs.

**Comment by rwultsch** [comment]
If you want to use this code and track our dev, we can figure out interfaces that for both of us. Are you? If so, which bits of our code?

**Pull request closed without merging**
